# Welcome to Jekyll!
# Website settings
title: Gaurav J.
description: Gaurav Joshi personal site.
keywords: micro,services,cloud,spring,boot,aws,dropwizard,oss,agile
# if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
baseurl: /
# url should be 'http://<github_username>.github.io/homepage' as before
url: https://kalpsnuti.github.io
# url: http://127.0.0.1:4000
# url should be '/homepage/static/assets/img/blog' as before
img_path: /static/assets/img/blog

# author -- index page "about me" section
# change following line to your infomation.
author:
  # Be used at blog posts' author.
  name: Gaurav J.
  # Be used at index page about me section.
  first_name: Gaurav
  # Be used at index page about me section.
  last_name: Joshi
  # upload your avatar at directory and edit it.
  avatar: static/assets/img/landing/avatar.jpg
  # Leave blank if you don't have now
  github_username: gaurrav-j
  # Leave blank if you don't have now
  linkedin_id: shabdsnuti
  facebook_username: shabdsnuti# Leave blank if you don't have now
  # Leave blank if you don't have now
  twitter_username: shabdsnuti
  # Leave blank if you don't have now
  email: gaurav.joshi@email.com
  # An online CV can be printed as PDF, leave blank if you don't have now
  cv:
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  primary_icons:
    - name: icon-java-bold
    - name: icon-reactjs
  secondary_icons:
    - name: icon-aws
    - name: icon-docker
  # Describe yourself.
  desc: java based architecture\'s & cloud native applications

# comment
# if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
#disqus:
#  name: jalpc

## google analytics - if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
ga:
  #id: UA-93473370-3

## google optimize
go:
  #id:

##growingIO - if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
gio:
  #id:

## donation type 'on'/'off' to choice display donation button at post page or not
donation: off

## carousels
# index page carousel switch
index_carousel: on
# blog page carousel switch
blog_carousel: on

##############################
# Dynamic Text on the Header #
##############################
dynamic-typing: True
# Shuffle the lines.
loop: True
# Set False for infinite loop, or set any number for finite loop.
start-delay: 2500
type-speed: 2500
delete-delay: 5000
# You can add HTML Tags in the Text
lines:
  - text: "deep-dive the microservices waters"
  - text: "explore functional/reactive applications & ui/ux stuff"
  - text: "Individuals and interactions over processes and tools"
  - text: "Working software over comprehensive documentation"

#Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing or learning to do.

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
